api_version = "2025-07"

[[extensions]]
name = "Bundle Cart Discount Function"
handle = "bundle-cart-discount-function"

uid = "d21a066f-25d9-97ef-1ebc-8e679c617ef3af1e4f84"

type = "function"
description = "Apply bundle-based cart line discounts."

[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/bundle_cart_discount_generate_run.graphql"
export = "bundle-cart-discount-generate-run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.access]
scopes = "write_discounts"