# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "779f3f7ae4a4fcb575c5a1d379ee9926"
name = "Ciwi LensFlow AI Test"
application_url = "https://bogdaapps-dnz0.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_app_proxy,write_products,write_purchase_options"

[auth]
redirect_urls = [ "https://bogdaapps-dnz0.onrender.com/api/auth" ]
