# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d6ecf37c020f88f5f01305cfb8127b26"
name = "Ciwi LensFlow AI"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_app_proxy,write_purchase_options,write_own_subscription_contracts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "/proxy/lens-options"
subpath = "lens-options"
prefix = "apps"
