// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/proxy/prescription-recommendations": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/proxy/purchase-records": {
    params: {};
  };
  "/proxy/product-match": {
    params: {};
  };
  "/proxy/lens-options": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/subscription-contracts": {
    params: {};
  };
  "/app/parameter-templates": {
    params: {};
  };
  "/app/product-configs": {
    params: {};
  };
  "/app/recommendations": {
    params: {};
  };
  "/app/notifications": {
    params: {};
  };
  "/app/subscriptions": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/prototype": {
    params: {};
  };
  "/app/orders": {
    params: {};
  };
  "/app/rules": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/proxy/prescription-recommendations" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/proxy/purchase-records" | "/proxy/product-match" | "/proxy/lens-options" | "/auth/login" | "/auth/*" | "/app" | "/app/subscription-contracts" | "/app/parameter-templates" | "/app/product-configs" | "/app/recommendations" | "/app/notifications" | "/app/subscriptions" | "/app/additional" | "/app/prototype" | "/app/orders" | "/app/rules";
  };
  "routes/proxy.prescription-recommendations.ts": {
    id: "routes/proxy.prescription-recommendations";
    page: "/proxy/prescription-recommendations";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/proxy.purchase-records.ts": {
    id: "routes/proxy.purchase-records";
    page: "/proxy/purchase-records";
  };
  "routes/proxy.product-match.ts": {
    id: "routes/proxy.product-match";
    page: "/proxy/product-match";
  };
  "routes/proxy.lens-options.ts": {
    id: "routes/proxy.lens-options";
    page: "/proxy/lens-options";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/subscription-contracts" | "/app/parameter-templates" | "/app/product-configs" | "/app/recommendations" | "/app/notifications" | "/app/subscriptions" | "/app/additional" | "/app/prototype" | "/app/orders" | "/app/rules";
  };
  "routes/app.subscription-contracts.tsx": {
    id: "routes/app.subscription-contracts";
    page: "/app/subscription-contracts";
  };
  "routes/app.parameter-templates.tsx": {
    id: "routes/app.parameter-templates";
    page: "/app/parameter-templates";
  };
  "routes/app.product-configs.tsx": {
    id: "routes/app.product-configs";
    page: "/app/product-configs";
  };
  "routes/app.recommendations.tsx": {
    id: "routes/app.recommendations";
    page: "/app/recommendations";
  };
  "routes/app.notifications.tsx": {
    id: "routes/app.notifications";
    page: "/app/notifications";
  };
  "routes/app.subscriptions.tsx": {
    id: "routes/app.subscriptions";
    page: "/app/subscriptions";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.prototype.tsx": {
    id: "routes/app.prototype";
    page: "/app/prototype";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.orders.tsx": {
    id: "routes/app.orders";
    page: "/app/orders";
  };
  "routes/app.rules.tsx": {
    id: "routes/app.rules";
    page: "/app/rules";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/proxy.prescription-recommendations": typeof import("./app/routes/proxy.prescription-recommendations.ts");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/proxy.purchase-records": typeof import("./app/routes/proxy.purchase-records.ts");
  "routes/proxy.product-match": typeof import("./app/routes/proxy.product-match.ts");
  "routes/proxy.lens-options": typeof import("./app/routes/proxy.lens-options.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.subscription-contracts": typeof import("./app/routes/app.subscription-contracts.tsx");
  "routes/app.parameter-templates": typeof import("./app/routes/app.parameter-templates.tsx");
  "routes/app.product-configs": typeof import("./app/routes/app.product-configs.tsx");
  "routes/app.recommendations": typeof import("./app/routes/app.recommendations.tsx");
  "routes/app.notifications": typeof import("./app/routes/app.notifications.tsx");
  "routes/app.subscriptions": typeof import("./app/routes/app.subscriptions.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.prototype": typeof import("./app/routes/app.prototype.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.orders": typeof import("./app/routes/app.orders.tsx");
  "routes/app.rules": typeof import("./app/routes/app.rules.tsx");
};