# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab25ea895c6df574ae9ff70e9c7731c5"
name = "Ciwi:bundlev2(Test)"
application_url = "https://bundlev2.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_discounts,write_metafields,read_metafields,read_products,write_pixels,read_customer_events,read_themes,read_markets"

[auth]
redirect_urls = [
  "https://bundlev2.onrender.com/auth/callback",
  "https://bundlev2.onrender.com/auth/shopify/callback",
  "https://bundlev2.onrender.com/api/auth/callback"
]
